openapi: 3.0.0
info:
  x-skaffolder-id-project: 6148be2dfe3329053d4d6cec
  title: MYCRM
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  /employee:
    post:
      x-skaffolder-id: 6148bf91fe3329053d4d6d74
      x-skaffolder-name: create
      x-skaffolder-id-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-resource: Employee
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - Employee
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Department:
                  type: string
                Location:
                  type: string
                Name:
                  type: string
                Role:
                  type: string
                Salary:
                  type: number
    get:
      x-skaffolder-id: 6148bf91fe3329053d4d6d7c
      x-skaffolder-name: list
      x-skaffolder-id-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-resource: Employee
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - Employee
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
  "/employee/{id}":
    delete:
      x-skaffolder-id: 6148bf91fe3329053d4d6d7a
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-resource: Employee
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - Employee
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 6148bf91fe3329053d4d6d77
      x-skaffolder-name: get
      x-skaffolder-id-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-resource: Employee
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - Employee
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
    post:
      x-skaffolder-id: 6148bf91fe3329053d4d6d75
      x-skaffolder-name: update
      x-skaffolder-id-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-resource: Employee
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - Employee
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
  "/employee/me":
    get:
      x-skaffolder-id: 6148bfd5fe3329053d4d6d7d
      x-skaffolder-name: me
      x-skaffolder-id-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-resource: Employee
      x-skaffolder-crudAction: 
      x-skaffolder-crudType: 
      x-skaffolder-description: get my profile
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: Boolean
      x-skaffolder-url: /me
      x-skaffolder-roles: []
      summary: get my profile
      tags:
        - Employee
      responses:
        "200":
          description: OK
  "/user/{id}/changePassword":
    post:
      x-skaffolder-id: 6148be2efe3329053d4d6cf9
      x-skaffolder-name: changePassword
      x-skaffolder-id-resource: 6148be2dfe3329053d4d6cf6
      x-skaffolder-resource: User
      x-skaffolder-crudAction: 
      x-skaffolder-crudType: 
      x-skaffolder-description: Change password of user from admin
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: object
      x-skaffolder-url: /{id}/changePassword
      x-skaffolder-roles:
        - 6148be2efe3329053d4d6cf8
      summary: Change password of user from admin
      tags:
        - User
      responses:
        "200":
          description: OK
  /user:
    post:
      x-skaffolder-id: 6148be2efe3329053d4d6cfa
      x-skaffolder-name: create
      x-skaffolder-id-resource: 6148be2dfe3329053d4d6cf6
      x-skaffolder-resource: User
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                name:
                  type: string
                password:
                  type: string
                roles:
                  type: string
                surname:
                  type: string
                username:
                  type: string
    get:
      x-skaffolder-id: 6148be2efe3329053d4d6cfd
      x-skaffolder-name: list
      x-skaffolder-id-resource: 6148be2dfe3329053d4d6cf6
      x-skaffolder-resource: User
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  "/user/{id}":
    delete:
      x-skaffolder-id: 6148be2efe3329053d4d6cfe
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 6148be2dfe3329053d4d6cf6
      x-skaffolder-resource: User
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 6148be2efe3329053d4d6cfc
      x-skaffolder-name: get
      x-skaffolder-id-resource: 6148be2dfe3329053d4d6cf6
      x-skaffolder-resource: User
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      x-skaffolder-id: 6148be2efe3329053d4d6cfb
      x-skaffolder-name: update
      x-skaffolder-id-resource: 6148be2dfe3329053d4d6cf6
      x-skaffolder-resource: User
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Employee:
      x-skaffolder-id: 6148bf7dfe3329053d4d6d71
      x-skaffolder-id-db: 6148be2dfe3329053d4d6ced
      x-skaffolder-id-entity: 6148bf7dfe3329053d4d6d6b
      x-skaffolder-url: /employee
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        Department:
          type: string
          x-skaffolder-id-attr: 6148bf7dfe3329053d4d6d6d
          x-skaffolder-type: String
          x-skaffolder-required: true
        Location:
          type: string
          x-skaffolder-id-attr: 6148bf7dfe3329053d4d6d70
          x-skaffolder-type: String
          x-skaffolder-required: true
        Name:
          type: string
          x-skaffolder-id-attr: 6148bf7dfe3329053d4d6d6c
          x-skaffolder-type: String
          x-skaffolder-required: true
        Role:
          type: string
          x-skaffolder-id-attr: 6148bf7dfe3329053d4d6d6e
          x-skaffolder-type: String
          x-skaffolder-required: true
        Salary:
          type: number
          x-skaffolder-id-attr: 6148bf7dfe3329053d4d6d6f
          x-skaffolder-type: Number
          x-skaffolder-required: true
      x-skaffolder-relations: 
      required:
        - _id
        - Department
        - Location
        - Name
        - Role
        - Salary
    User:
      x-skaffolder-id: 6148be2dfe3329053d4d6cf6
      x-skaffolder-id-db: 6148be2dfe3329053d4d6ced
      x-skaffolder-id-entity: 6148be2dfe3329053d4d6cee
      x-skaffolder-url: /user
      x-skaffolder-type: User
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        mail:
          type: string
          x-skaffolder-id-attr: 6148be2dfe3329053d4d6cf1
          x-skaffolder-type: String
        name:
          type: string
          x-skaffolder-id-attr: 6148be2dfe3329053d4d6cf2
          x-skaffolder-type: String
        password:
          type: string
          x-skaffolder-id-attr: 6148be2dfe3329053d4d6cf0
          x-skaffolder-type: String
          x-skaffolder-required: true
        roles:
          type: string
          x-skaffolder-id-attr: 6148be2dfe3329053d4d6cf4
          x-skaffolder-type: String
        surname:
          type: string
          x-skaffolder-id-attr: 6148be2dfe3329053d4d6cf3
          x-skaffolder-type: String
        username:
          type: string
          x-skaffolder-id-attr: 6148be2dfe3329053d4d6cef
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
      required:
        - _id
        - password
        - username
  x-skaffolder-db:
    - x-skaffolder-id: 6148be2dfe3329053d4d6ced
      x-skaffolder-name: MYCRM_db
  x-skaffolder-page:
    - x-skaffolder-id: 6148bf91fe3329053d4d6d73
      x-skaffolder-name: EmployeeEdit
      x-skaffolder-url: /employees/{id}
      x-skaffolder-template: Edit_Crud
      x-skaffolder-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-services:
        - 6148bf91fe3329053d4d6d74
        - 6148bf91fe3329053d4d6d75
        - 6148bf91fe3329053d4d6d77
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 6148bf91fe3329053d4d6d79
      x-skaffolder-name: EmployeeList
      x-skaffolder-url: /employees
      x-skaffolder-template: List_Crud
      x-skaffolder-resource: 6148bf7dfe3329053d4d6d71
      x-skaffolder-services:
        - 6148bf91fe3329053d4d6d7a
        - 6148bf91fe3329053d4d6d7c
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 6148bf91fe3329053d4d6d73
      x-skaffolder-roles: []
    - x-skaffolder-id: 6148be2dfe3329053d4d6cf5
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 6148bf91fe3329053d4d6d79
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 6148be2efe3329053d4d6cf8
      x-skaffolder-name: ADMIN
